### PR TITLE
bump darling to 0.14.4

### LINKED ISSUE #25: Error::description() deprecated, should use Display trait (causes Runtime exception?!)
Hi there! I just started using your library, and it worked perfectly well the first time I used it (2 days ago). The IDE was complaining about `description()` being deprecated, but it was only a warning and everything was working perfectly.

However now I'm getting a `RuntimeException` in Java whenever I try to call my JNI function, with the following message:

`java.lang.RuntimeException: JNI call error!. Cause: description() is deprecated; use Display`

This is quite confusing, because why on earth is this compile-time check inside the generated shared library file itself?! I couldn't really figure out what's causing this.

My only hypothesis for now is that the `Error::description()` function is automatically populated with that message to get the attention of developers to use `Display` instead, which makes it useless to understand what's going on under-the-hood.

### LINKED ISSUE #29: `pub` keyword in "jni" functions causing weird compiler error about unrelated code.
I am trying to set up a project using the `robusta_jni` crate, and today I started seeing a weird issue where the `pub` keyword in my "jni" (implemented on the rust side of the program) function causes a compiler error. The rust diagnostic looks like this:
```
error[E0599]: no method named `description` found for enum `robusta_jni::jni::errors::Error` in the current scope
   --> src\lib.rs:13:9
    |
13  |         pub extern "jni" fn printFromRust() -> JniResult<()> {
    |         ^^^ method not found in `Error`
    |
   ::: C:\Users\MY_NAME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\error.rs:110:8
    |
110 |     fn description(&self) -> &str {
    |        ----------- the method is available for `robusta_jni::jni::errors::Error` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
5   +     use std::error::Error;
    |
```

Meanwhile, the code that's causing the error is very simple (because I'm just trying to make sure everything works at this point). The file it's in doesn't even use `robusta_jni::jni::errors::Error`.
```
...
pub extern "jni" fn printFromRust() -> JniResult<()> {
    println!("Rust called from Java.");
    Ok(())
}
```

Adding the `use` statement like the diagnostic suggests turns the error into a warning about the `description` method being deprecated, and this may be what I have to do for now to get the code to build.

I also tried copying and pasting the example code from this GitHub repo into the file and all of the "jni" functions in that code had the exact same issue, which is why I think it may be a bug in the `robusta_jni` crate. The last time the code didn't have this issue was before Rust 1.70 was released, so maybe that update broke something,

### PR DESCRIPTION
**Pull request by DarkKirb**
Fixes #25
Fixes #29

### CODE REVIEW

**Comment by HyperAlch** [comment]
Pull request has been open, waiting for approval for 3 weeks. Project dead?

**Review by EliseChouleur — APPROVED** [review]

**Comment by EliseChouleur** [comment]
I'm not an expert on JNI on Desktop side, so not sure how to reproduce linked errors.
But always nice to update dependencies ;)

**Comment by Skaldebane** [comment]
@giovanniberti if this fixes those issues, please merge it ASAP 🙏🏻 I hope the project isn't dead and/or abandoned.

**Comment by EliseChouleur** [comment]
I've added a dependabot on cargo ;)

**Pull request closed without merging**
